In [1]:
# import libraries
import piplite
await piplite.install('seaborn')

import pandas as pd
import numpy as np


import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# open the first file
url = r"Data/EloRatings.csv"
df1 = pd.read_csv(url) #to loud file
df1

date       club country      elo
0       2000-07-01     Aachen     GER  1453.60
1       2000-07-01    Aalborg     DEN  1482.61
2       2000-07-01      Aalst     BEL  1337.53
3       2000-07-01     Aarhus     DEN  1381.46
4       2000-07-01   Aberdeen     SCO  1360.43
...            ...        ...     ...      ...
245028  2025-06-01  Wolfsburg     GER  1645.72
245029  2025-06-01     Wolves     ENG  1735.76
245030  2025-06-01   Zaragoza     ESP  1450.09
245031  2025-06-01      Zenit     RUS  1654.94
245032  2025-06-01     Zwolle     NED  1462.81

[245033 rows x 4 columns]

In [3]:
# Data Informations in file 1
df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245033 entries, 0 to 245032
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   date     245033 non-null  object 
 1   club     245033 non-null  object 
 2   country  245033 non-null  object 
 3   elo      245033 non-null  float64
dtypes: float64(1), object(3)
memory usage: 4.7+ MB


elo
count  245033.000000
mean     1505.072948
std       155.587668
min      1069.680000
25%      1394.720000
50%      1486.820000
75%      1606.010000
max      2107.480000

In [4]:
# Data Understanding in file 1
print("Missing Values:\n", df1.isnull().sum())
print("\nDuplicate Rows:", df1.duplicated().sum())

Missing Values:
 date       0
club       0
country    0
elo        0
dtype: int64

Duplicate Rows: 0


In [5]:
# Data Types in file 1
df1.dtypes

date        object
club        object
country     object
elo        float64
dtype: object

In [6]:
# View columns in file 1
df1.columns

Index(['date', 'club', 'country', 'elo'], dtype='object')

In [7]:
# Check values in Column1 in file 1
df1["date"].unique()

array(['2000-07-01', '2000-07-15', '2000-08-01', '2000-08-15',
       '2000-09-01', '2000-09-15', '2000-10-01', '2000-10-15',
       '2000-11-01', '2000-11-15', '2000-12-01', '2000-12-15',
       '2001-01-01', '2001-01-15', '2001-02-01', '2001-02-15',
       '2001-03-01', '2001-03-15', '2001-04-01', '2001-04-15',
       '2001-05-01', '2001-05-15', '2001-06-01', '2001-06-15',
       '2001-07-01', '2001-07-15', '2001-08-01', '2001-08-15',
       '2001-09-01', '2001-09-15', '2001-10-01', '2001-10-15',
       '2001-11-01', '2001-11-15', '2001-12-01', '2001-12-15',
       '2002-01-01', '2002-01-15', '2002-02-01', '2002-02-15',
       '2002-03-01', '2002-03-15', '2002-04-01', '2002-04-15',
       '2002-05-01', '2002-05-15', '2002-06-01', '2002-06-15',
       '2002-07-01', '2002-07-15', '2002-08-01', '2002-08-15',
       '2002-09-01', '2002-09-15', '2002-10-01', '2002-10-15',
       '2002-11-01', '2002-11-15', '2002-12-01', '2002-12-15',
       '2003-01-01', '2003-01-15', '2003-02-01', '2003-

In [8]:
# Check values in Column2 in file 1
df1["club"].unique()

array(['Aachen', 'Aalborg', 'Aalst', 'Aarhus', 'Aberdeen', 'Adanaspor',
       'AEK', 'AIK', 'Ajaccio', 'Ajax', 'Akademisk', 'Alanya', 'Alaves',
       'Albacete', 'Altay', 'Alverca', 'Alzano', 'Amica Wronki', 'Amiens',
       'Anderlecht', 'Ankaraguecue', 'Antalyaspor', 'Anzhi', 'Apollon',
       'Arges Pitesti', 'Aris', 'Arsenal', 'Aston Villa', 'Astra',
       'Atalanta', 'Ath Bilbao', 'Ath Madrid', 'Atletico B',
       'Austria Wien', 'Auxerre', 'AZ Alkmaar', 'Bacau', 'Badajoz',
       'Barcelona', 'Bari', 'Barnsley', 'Bastia', 'Bayern Munich',
       'Beerschot VA', 'Beira Mar', 'Belenenses', 'Benfica', 'Besiktas',
       'Betis', 'Beveren', 'Bielefeld', 'Birmingham', 'Bistrita',
       'Blackburn', 'Boavista', 'Bochum', 'Bodoe Glimt', 'Bologna',
       'Bolton', 'Bordeaux', 'Bradford', 'Brann', 'Brasov', 'Bregenz',
       'Brescia', 'Brondby', 'Bryne', 'Bursaspor', 'Caen', 'Cagliari',
       'Cambuur', 'Campomaiorense', 'Cannes', 'Celta', 'Celtic', 'Cesena',
       'Charleroi', '

In [9]:
# Check values in Column3 in file 1
df1["country"].unique()

array(['GER', 'DEN', 'BEL', 'SCO', 'TUR', 'GRE', 'SWE', 'FRA', 'NED',
       'RUS', 'ESP', 'POR', 'ITA', 'POL', 'ROM', 'ENG', 'AUT', 'NOR',
       'FIN'], dtype=object)

In [10]:
# Check values in Column4 in file 1
df1["elo"].unique()

array([1453.6 , 1482.61, 1337.53, ..., 1331.06, 1785.55, 1645.72],
      shape=(60668,))

In [11]:
# Drop Duplicates in file 1 (if data have duplicates but this df have not duplicates)
df1.drop_duplicates(inplace=True)

In [12]:
# Final Validation for file 1
print(df1.isnull().sum())
print(" ")
print(df1.describe())
print(" ")
print(df1.dtypes)

date       0
club       0
country    0
elo        0
dtype: int64
 
                 elo
count  245033.000000
mean     1505.072948
std       155.587668
min      1069.680000
25%      1394.720000
50%      1486.820000
75%      1606.010000
max      2107.480000
 
date        object
club        object
country     object
elo        float64
dtype: object


In [13]:
# open the second file
url = r"Data/Matches.csv"
df2 = pd.read_csv(url) #to loud file
df2

<ipython-input-13-d135db2ebc01>:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(url) #to loud file


Division   MatchDate MatchTime   HomeTeam    AwayTeam  HomeElo  \
0            F1  2000-07-28       NaN  Marseille      Troyes  1686.34   
1            F1  2000-07-28       NaN   Paris SG  Strasbourg  1714.89   
2            F2  2000-07-28       NaN  Wasquehal       Nancy  1465.08   
3            F1  2000-07-29       NaN    Auxerre       Sedan  1635.58   
4            F1  2000-07-29       NaN   Bordeaux        Metz  1734.34   
...         ...         ...       ...        ...         ...      ...   
230552      SP2  2025-06-01  17:30:00  Cartagena    Mirandes  1339.21   
230553      SP2  2025-06-01  17:30:00    Almeria    Tenerife  1544.16   
230554      SP2  2025-06-01  17:30:00  La Coruna       Elche  1473.67   
230555      SP2  2025-06-01  17:30:00     Oviedo       Cadiz  1574.90   
230556      SP2  2025-06-01  20:00:00    Cordoba    Albacete  1468.40   

        AwayElo  Form3Home  Form5Home  Form3Away  ...  MaxUnder25  HandiSize  \
0       1586.57        0.0        0.0        0.0  ...         NaN        NaN   
1       1642.51        0.0        0.0        0.0  ...         NaN        NaN   
2       1633.80        0.0        0.0        0.0  ...         NaN        NaN   
3       1624.22        0.0        0.0        0.0  ...         NaN        NaN   
4       1673.11        0.0        0.0        0.0  ...         NaN        NaN   
...         ...        ...        ...        ...  ...         ...        ...   
230552  1544.15        3.0        6.0        7.0  ...        2.40        1.8   
230553  1433.67        4.0       10.0        1.0  ...        2.55       -1.8   
230554  1569.98        0.0        3.0        3.0  ...        2.63        1.3   
230555  1525.76        7.0       13.0        6.0  ...        1.51       -0.8   
230556  1495.25        0.0        4.0        6.0  ...        2.70       -1.0   

        HandiHome HandiAway   C_LTH   C_LTA   C_VHD   C_VAD   C_HTB   C_PHB  
0             NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
1             NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
2             NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
3             NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
4             NaN       NaN     NaN     NaN     NaN     NaN     NaN     NaN  
...           ...       ...     ...     ...     ...     ...     ...     ...  
230552       1.95      1.85  0.0209  0.0118  0.0099  0.8084  0.1386  0.0104  
230553       1.80      2.00  0.3799  0.0630  0.2806  0.0160  0.2332  0.0274  
230554       1.78      2.03  0.0224  0.7482  0.0100  0.1201  0.0180  0.0813  
230555       1.95      1.85  0.2070  0.2490  0.2334  0.0211  0.2634  0.0261  
230556       2.00      1.80  0.0191  0.0203  0.0937  0.0164  0.8251  0.0254  

[230557 rows x 48 columns]

In [14]:
# Data Informations in file 2
df2.info()
df2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230557 entries, 0 to 230556
Data columns (total 48 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Division     230557 non-null  object 
 1   MatchDate    230557 non-null  object 
 2   MatchTime    99072 non-null   object 
 3   HomeTeam     230557 non-null  object 
 4   AwayTeam     230557 non-null  object 
 5   HomeElo      141597 non-null  float64
 6   AwayElo      141528 non-null  float64
 7   Form3Home    229057 non-null  float64
 8   Form5Home    229057 non-null  float64
 9   Form3Away    229057 non-null  float64
 10  Form5Away    229057 non-null  float64
 11  FTHome       230554 non-null  float64
 12  FTAway       230554 non-null  float64
 13  FTResult     230554 non-null  object 
 14  HTHome       175977 non-null  float64
 15  HTAway       175977 non-null  float64
 16  HTResult     175977 non-null  object 
 17  HomeShots    114735 non-null  float64
 18  AwayShots    114738 non-

HomeElo        AwayElo      Form3Home      Form5Home  \
count  141597.000000  141528.000000  229057.000000  229057.000000   
mean     1533.118663    1533.165652       3.984628       6.721606   
std       153.279601     153.294511       2.377010       3.257166   
min      1103.130000    1103.130000       0.000000       0.000000   
25%      1424.870000    1424.930000       2.000000       4.000000   
50%      1515.450000    1515.475000       4.000000       7.000000   
75%      1634.240000    1634.222500       6.000000       9.000000   
max      2107.480000    2107.480000       9.000000      15.000000   

           Form3Away      Form5Away         FTHome         FTAway  \
count  229057.000000  229057.000000  230554.000000  230554.000000   
mean        4.203482       6.928241       1.488411       1.150646   
std         2.393202       3.269548       1.258901       1.112735   
min         0.000000       0.000000       0.000000       0.000000   
25%         3.000000       4.000000       1.000000       0.000000   
50%         4.000000       7.000000       1.000000       1.000000   
75%         6.000000       9.000000       2.000000       2.000000   
max         9.000000      15.000000      10.000000      13.000000   

              HTHome         HTAway  ...     MaxUnder25      HandiSize  \
count  175977.000000  175977.000000  ...  148397.000000  156733.000000   
mean        0.657626       0.502782  ...       1.986764      -0.303375   
std         0.812627       0.715419  ...       0.719088       0.729464   
min         0.000000       0.000000  ...       1.260000     -99.900000   
25%         0.000000       0.000000  ...       1.750000      -0.500000   
50%         0.000000       0.000000  ...       1.910000      -0.300000   
75%         1.000000       1.000000  ...       2.120000       0.000000   
max         7.000000       7.000000  ...     238.000000      12.500000   

           HandiHome      HandiAway          C_LTH          C_LTA  \
count  156475.000000  156451.000000  112602.000000  112602.000000   
mean        1.919722       1.954644       0.216225       0.200979   
std         0.495534       0.351741       0.242283       0.239103   
min         0.000000      -0.500000       0.009700       0.009700   
25%         1.830000       1.830000       0.036000       0.032000   
50%         1.920000       1.930000       0.102700       0.086300   
75%         2.010000       2.020000       0.325100       0.286100   
max       177.000000      15.140000       0.943700       0.944900   

               C_VHD          C_VAD          C_HTB          C_PHB  
count  112602.000000  112602.000000  112602.000000  112602.000000  
mean        0.146727       0.126160       0.173664       0.136246  
std         0.230572       0.216921       0.214677       0.199302  
min         0.009800       0.009700       0.009800       0.009700  
25%         0.011400       0.010000       0.031100       0.021400  
50%         0.036100       0.027100       0.073500       0.046800  
75%         0.154900       0.112600       0.225300       0.147000  
max         0.951200       0.951100       0.946500       0.941500  

[8 rows x 41 columns]

In [15]:
# Data Understanding in file 2
print("Missing Values:\n", df2.isnull().sum())
print("\nDuplicate Rows:", df2.duplicated().sum())

Missing Values:
 Division            0
MatchDate           0
MatchTime      131485
HomeTeam            0
AwayTeam            0
HomeElo         88960
AwayElo         89029
Form3Home        1500
Form5Home        1500
Form3Away        1500
Form5Away        1500
FTHome              3
FTAway              3
FTResult            3
HTHome          54580
HTAway          54580
HTResult        54580
HomeShots      115822
AwayShots      115819
HomeTarget     116628
AwayTarget     116625
HomeFouls      116584
AwayFouls      116584
HomeCorners    116194
AwayCorners    116194
HomeYellow     111259
AwayYellow     111258
HomeRed        111258
AwayRed        111260
OddHome          3030
OddDraw          3030
OddAway          3030
MaxHome         27635
MaxDraw         27635
MaxAway         27635
Over25          82159
Under25         82160
MaxOver25       82159
MaxUnder25      82160
HandiSize       73824
HandiHome       74082
HandiAway       74106
C_LTH          117955
C_LTA          117955
C_VHD          

In [16]:
# Data Types in file 2
df2.dtypes

Division        object
MatchDate       object
MatchTime       object
HomeTeam        object
AwayTeam        object
HomeElo        float64
AwayElo        float64
Form3Home      float64
Form5Home      float64
Form3Away      float64
Form5Away      float64
FTHome         float64
FTAway         float64
FTResult        object
HTHome         float64
HTAway         float64
HTResult        object
HomeShots      float64
AwayShots      float64
HomeTarget     float64
AwayTarget     float64
HomeFouls      float64
AwayFouls      float64
HomeCorners    float64
AwayCorners    float64
HomeYellow     float64
AwayYellow     float64
HomeRed        float64
AwayRed        float64
OddHome        float64
OddDraw        float64
OddAway        float64
MaxHome        float64
MaxDraw        float64
MaxAway        float64
Over25         float64
Under25        float64
MaxOver25      float64
MaxUnder25     float64
HandiSize      float64
HandiHome      float64
HandiAway      float64
C_LTH          float64
C_LTA      

In [17]:
# Check Null Values in file 2

# Count Null Values
null_count = df2.isnull().sum()

# Count Null Percentage
null_percentage = (df2.isnull().mean() * 100).round(2)

# Merge it in one table
missing_report = pd.DataFrame({
    "Missing Count": null_count,
    "Missing Percentage %": null_percentage
})

print(missing_report)

             Missing Count  Missing Percentage %
Division                 0                  0.00
MatchDate                0                  0.00
MatchTime           131485                 57.03
HomeTeam                 0                  0.00
AwayTeam                 0                  0.00
HomeElo              88960                 38.58
AwayElo              89029                 38.61
Form3Home             1500                  0.65
Form5Home             1500                  0.65
Form3Away             1500                  0.65
Form5Away             1500                  0.65
FTHome                   3                  0.00
FTAway                   3                  0.00
FTResult                 3                  0.00
HTHome               54580                 23.67
HTAway               54580                 23.67
HTResult             54580                 23.67
HomeShots           115822                 50.24
AwayShots           115819                 50.23
HomeTarget          

In [25]:
# Drop Columns in file 2 have > 25% null values
cols_to_drop = df2.columns[df2.isnull().mean() > 0.25]
print("Columns to drop:", cols_to_drop)

Columns to drop: Index(['MatchTime', 'HomeElo', 'AwayElo', 'HomeShots', 'AwayShots',
       'HomeTarget', 'AwayTarget', 'HomeFouls', 'AwayFouls', 'HomeCorners',
       'AwayCorners', 'HomeYellow', 'AwayYellow', 'HomeRed', 'AwayRed',
       'Over25', 'Under25', 'MaxOver25', 'MaxUnder25', 'HandiSize',
       'HandiHome', 'HandiAway', 'C_LTH', 'C_LTA', 'C_VHD', 'C_VAD', 'C_HTB',
       'C_PHB'],
      dtype='object')


In [26]:
# View columns in file 2
df2 = df2.drop(columns=cols_to_drop)
df2.columns

Index(['Division', 'MatchDate', 'HomeTeam', 'AwayTeam', 'Form3Home',
       'Form5Home', 'Form3Away', 'Form5Away', 'FTHome', 'FTAway', 'FTResult',
       'HTHome', 'HTAway', 'HTResult', 'OddHome', 'OddDraw', 'OddAway',
       'MaxHome', 'MaxDraw', 'MaxAway'],
      dtype='object')

In [27]:
# Check values in Column "Division" in file 2
df2["Division"].unique()

array(['F1', 'F2', 'T1', 'D1', 'D2', 'B1', 'E2', 'E1', 'N1', 'P1', 'E0',
       'I2', 'SP2', 'SP1', 'I1', 'E3', 'SC0', 'SC1', 'SC2', 'SC3', 'G1',
       'EC', 'USA', 'SWE', 'NOR', 'IRL', 'BRA', 'ARG', 'MEX', 'JAP',
       'RUS', 'POL', 'DEN', 'ROM', 'AUT', 'SUI', 'FIN', 'CHN'],
      dtype=object)

In [28]:
# Check values in Column "MatchDate" in file 2
df2["MatchDate"].unique()

array(['2000-07-28', '2000-07-29', '2000-08-03', ..., '2025-05-30',
       '2025-05-31', '2025-06-01'], shape=(7402,), dtype=object)

In [30]:
# Check values in Column "HomeTeam" in file 2
df2["HomeTeam"].unique()

array(['Marseille', 'Paris SG', 'Wasquehal', ..., "Nott'm Forest",
       "M'gladbach", 'Preußen Münster'], shape=(1214,), dtype=object)

In [31]:
# Check values in Column "AwayTeam" in file 2
df2["AwayTeam"].unique()

array(['Troyes', 'Strasbourg', 'Nancy', ..., "Nott'm Forest",
       "M'gladbach", 'Preußen Münster'], shape=(1206,), dtype=object)

In [34]:
# Check values in Column "Form3Home" in file 2
df2 = df2[df2["Form3Home"].notnull()]
df2["Form3Home"].unique()

array([0., 9., 3., 5., 2., 6., 7., 4., 1.])

In [35]:
# Check values in Column "Form5Home" in file 2
df2 = df2[df2["Form5Home"].notnull()]
df2["Form3Home"].unique()

array([0., 9., 3., 5., 2., 6., 7., 4., 1.])

In [36]:
# Check values in Column "Form3ِAway" in file 2
df2 = df2[df2["Form3Away"].notnull()]
df2["Form3Away"].unique()

array([0., 3., 9., 2., 5., 6., 1., 7., 4.])

In [37]:
# Check values in Column "Form5Away" in file 2
df2 = df2[df2["Form5Away"].notnull()]
df2["Form5Away"].unique()

array([ 0.,  5., 15.,  3.,  8., 10.,  2., 12.,  7., 13.,  6.,  1.,  9.,
       11.,  4.])

In [40]:
# Check values in Column "FTHome" in file 2
df2 = df2[df2["FTHome"].notnull()]
df2["FTHome"].unique()

array([ 3.,  0.,  1.,  2.,  6.,  5.,  4.,  7.,  8.,  9., 10.])

In [41]:
# Check values in Column "FTAway" in file 2
df2 = df2[df2["FTAway"].notnull()]
df2["FTAway"].unique()

array([ 1.,  2.,  0.,  3.,  5.,  4.,  6.,  7.,  8.,  9., 13.])

In [42]:
# Check values in Column "FTResult" in file 2
df2 = df2[df2["FTResult"].notnull()]
df2["FTResult"].unique()

array(['H', 'A', 'D'], dtype=object)

In [43]:
# Check values in Column "HTHome" in file 2
df2 = df2[df2["HTHome"].notnull()]
df2["HTHome"].unique()

array([2., 1., 0., 3., 4., 6., 5., 7.])

In [44]:
# Check values in Column "HTAway" in file 2
df2 = df2[df2["HTAway"].notnull()]
df2["HTAway"].unique()

array([1., 0., 2., 4., 3., 6., 5., 7.])

In [45]:
# Check values in Column "HTResult" in file 2
df2 = df2[df2["HTResult"].notnull()]
df2["HTResult"].unique()

array(['H', 'D', 'A'], dtype=object)

In [46]:
# Check values in Column "OddHome" in file 2
df2 = df2[df2["OddHome"].notnull()]
df2["OddHome"].unique()

array([ 1.65,  1.6 ,  1.7 , ..., 13.37,  9.85, 12.33], shape=(1104,))

In [47]:
# Check values in Column "OddDraw" in file 2
df2 = df2[df2["OddDraw"].notnull()]
df2["OddDraw"].unique()

array([ 3.3 ,  3.4 ,  3.  ,  3.1 ,  4.  ,  3.2 ,  3.05,  4.5 ,  3.6 ,
        3.7 ,  3.5 ,  4.1 ,  2.9 ,  2.95,  3.15,  4.2 ,  4.35,  3.25,
        2.8 ,  3.35,  4.3 ,  3.45,  3.65,  4.65,  3.8 ,  4.05,  5.  ,
        4.4 ,  3.75,  4.8 ,  3.9 ,  5.5 ,  3.55,  5.15,  4.7 ,  4.25,
        5.3 ,  5.2 ,  3.85,  5.75,  5.4 ,  6.5 ,  4.55,  3.66,  6.  ,
        4.6 ,  2.85,  2.7 ,  2.55,  2.5 ,  2.6 ,  2.65,  2.45,  2.4 ,
        2.75,  6.8 ,  5.8 ,  5.25,  4.9 ,  8.  ,  5.7 ,  4.45,  4.75,
        2.92,  4.15,  5.1 ,  2.2 ,  3.95,  3.07,  2.15,  1.85,  2.35,
        2.62,  2.72,  7.  ,  3.53,  1.6 ,  6.75,  7.25,  6.25,  4.85,
        5.85,  6.15,  2.77,  5.35,  5.65,  5.45,  5.6 ,  6.2 ,  7.55,
        4.95,  7.15,  3.78,  5.95,  2.3 ,  2.1 ,  2.  ,  3.33,  5.05,
        2.33,  1.7 ,  2.88,  4.33,  2.63,  2.87,  7.5 ,  1.73,  2.37,
        8.5 ,  2.38,  2.79,  3.39,  2.89,  3.29,  3.79,  1.8 ,  1.66,
        1.83,  1.72,  1.9 ,  2.25,  1.61,  9.  ,  1.91,  1.4 ,  2.05,
        1.5 ,  1.44,

In [48]:
# Check values in Column "OddAway" in file 2
df2 = df2[df2["OddAway"].notnull()]
df2["OddAway"].unique()

array([ 4.3 ,  4.6 ,  3.9 , ..., 28.12, 21.58, 10.25], shape=(1767,))

In [49]:
# Check values in Column "MaxHome" in file 2
df2 = df2[df2["MaxHome"].notnull()]
df2["MaxHome"].unique()

array([ 1.6 ,  2.2 ,  2.1 , ..., 14.8 , 13.27,  9.99], shape=(1095,))

In [50]:
# Check values in Column "MaxDraw" in file 2
df2 = df2[df2["MaxDraw"].notnull()]
df2["MaxDraw"].unique()

array([ 3.85,  2.85,  3.1 ,  2.9 ,  3.2 ,  2.88,  3.25,  3.4 ,  3.15,
        3.5 ,  3.35,  3.65,  5.  ,  9.  ,  3.  ,  3.05,  3.6 ,  2.95,
        3.55,  6.  ,  3.45,  4.1 ,  4.6 ,  7.  ,  5.5 ,  3.39,  3.75,
        4.  ,  4.33,  3.8 ,  3.3 ,  3.29,  7.5 ,  3.9 ,  4.5 ,  4.4 ,
        3.42,  4.75,  3.7 ,  6.75,  3.63,  4.2 ,  4.8 ,  4.45,  5.3 ,
        4.31,  6.2 ,  4.85,  5.25,  5.6 ,  3.74,  3.27,  3.49,  3.56,
        3.62,  4.48,  3.32,  3.38,  4.32,  6.5 ,  2.87,  4.35,  5.15,
        3.79,  4.7 ,  5.96,  2.8 ,  2.75,  6.55,  5.55,  6.05,  8.  ,
        3.95,  6.25,  6.15,  4.17,  3.37,  5.75,  4.65,  5.8 ,  3.77,
        4.25,  3.21,  3.67,  6.4 ,  3.48,  3.53,  7.8 ,  5.9 ,  6.16,
        5.33,  3.78,  3.51,  3.47,  3.33,  3.59,  3.41,  5.2 ,  4.27,
        3.34,  3.44,  3.69,  4.93,  6.3 ,  3.43,  3.58,  5.05, 11.  ,
        5.73,  3.13,  3.31,  2.93,  3.61,  5.41,  6.27,  4.15,  4.05,
        3.76,  5.24,  2.96,  6.8 ,  4.3 ,  3.84,  4.64,  3.83,  4.55,
        5.94,  3.52,

In [51]:
# Check values in Column "MaxAway" in file 2
df2 = df2[df2["MaxAway"].notnull()]
df2["MaxAway"].unique()

array([ 9.  ,  4.3 ,  4.65, ..., 12.9 , 13.48, 15.79], shape=(1799,))

In [52]:
# Drop Duplicates in file 2
df2.drop_duplicates(inplace=True)

In [54]:
# Final Validation for file 2
print(df2.isnull().sum())
print(" ")
print(df2.describe())
print(" ")
print(df2.dtypes)

Division     0
MatchDate    0
HomeTeam     0
AwayTeam     0
Form3Home    0
Form5Home    0
Form3Away    0
Form5Away    0
FTHome       0
FTAway       0
FTResult     0
HTHome       0
HTAway       0
HTResult     0
OddHome      0
OddDraw      0
OddAway      0
MaxHome      0
MaxDraw      0
MaxAway      0
dtype: int64
 
           Form3Home     Form5Home      Form3Away      Form5Away  \
count  147794.000000  147794.00000  147794.000000  147794.000000   
mean        3.981860       6.72844       4.222100       6.946710   
std         2.369449       3.24129       2.388777       3.252671   
min         0.000000       0.00000       0.000000       0.000000   
25%         2.000000       4.00000       3.000000       5.000000   
50%         4.000000       7.00000       4.000000       7.000000   
75%         6.000000       9.00000       6.000000       9.000000   
max         9.000000      15.00000       9.000000      15.000000   

              FTHome         FTAway         HTHome         HTAway  \
cou

In [61]:
# Export Data to csv files
df1.to_csv("EloRatings.csv", index=False)
df2.to_csv("Matches.csv", index=False)